---
- name: Reload systemd
  become: yes
  command: systemctl daemon-reload
  notify: Restart etcd

- name: Restart etcd
  service: name={{etcd_service}} state=restarted
  ignore_errors: "{{ ignore_etcd_restart_errors }}"
  become: yes
